---
title: "Developing Analysis"
author: "Spencer Fox"
date: "1/18/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "../")
```

```{r ,include = FALSE}
library(cowplot)
library(tidyverse)
library(coda)
library(stringr)
sapply(c("R/fitting_fxns.R","R/load_data.R"), source)

```

## Current R0 Estimation Procedure

The current R0 estimation methods (Perkins 2016) provides estimates for Texas that are way to high.

```{r}
# Get data for plotting
source("R/calc_monthly_rnots.R")
head(tx_county)
aug_data <- tx_county %>% gather(rnot, value, low_r0:high_r0) %>%
  filter(month == "Aug") 
  
rnot_plot <- map_data(map = "county") %>% filter(region=="texas") %>% 
  mutate(subregion = if_else(subregion=="de witt", "dewitt", subregion)) %>%
  left_join(aug_data, by=c("subregion" = "county")) %>% 
  mutate(rnot = factor(rnot, levels = c("low_r0", "med_r0", "high_r0"))) %>%
  ggplot(aes(x=long, y=lat, fill = value, group = subregion)) + facet_wrap(~rnot)+
    geom_polygon(color = "gray", size=0.25) +
    scale_fill_gradient2(na.value="white", low = "blue", mid = "white", high = "red", trans="log10", midpoint=0)+
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank())
rnot_plot

save_plot("figs/rnot_distribution_map.pdf", rnot_plot, base_height = 4, base_aspect_ratio = 3)
rnot_plot

## Just median values
median_rnot_plot <- map_data(map = "county") %>% filter(region=="texas") %>% 
  mutate(subregion = if_else(subregion=="de witt", "dewitt", subregion)) %>%
  left_join(aug_data, by=c("subregion" = "county")) %>% 
  filter(rnot =="med_r0") %>%
  ggplot(aes(x=long, y=lat, fill = value, group = subregion)) + 
    geom_polygon(color = "gray", size=0.25) +
    scale_fill_gradient2(na.value="white", low = "blue", mid = "white", high = "red", trans="log10", midpoint=0)+
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank())
save_plot("figs/rnot_median_map.pdf", median_rnot_plot, base_height = 4, base_aspect_ratio = 1.3)
median_rnot_plot


# Median temperatures through time
month_data <- tx_county %>% gather(rnot, value, low_r0:high_r0) %>%
  filter(rnot=="med_r0") 

month_plot <- map_data(map = "county") %>% filter(region=="texas") %>% 
  mutate(subregion = if_else(subregion=="de witt", "dewitt", subregion)) %>%
  left_join(month_data, by=c("subregion" = "county")) %>% 
  mutate(value = if_else(value<0.01, 0, value)) %>%
  ggplot(aes(x=long, y=lat, fill = value, group = subregion)) + facet_wrap(~month)+
    geom_polygon(color = "gray", size=0.25) +
    scale_fill_gradient2(na.value="white", low = "blue", mid = "white", high = "red", trans="log10", midpoint=0)+
    theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank())
save_plot("figs/rnot_by_month.pdf", month_plot, base_height = 6, base_aspect_ratio = 1.3)
month_plot

# Temperature plot
rnot_seasonal_plot <- tx_county %>%
  ggplot(aes(month, med_r0, color = county, group=county)) + geom_line() +
  guides(color = FALSE) +
  labs(y = expression("Median R"[0]))
  
save_plot("figs/rnot_seasonal.pdf", rnot_seasonal_plot, base_height = 5, base_aspect_ratio = 1.8)
rnot_seasonal_plot



```

## Importation plots
```{r}
# tx_imports <- read_csv("data/ZikaReportDates11032016.csv")

# tx_imports <- tx_imports %>% mutate(county = tolower(county), str)

tx_cum_imports <- tx_imports %>% group_by(county) %>%
                    summarise(count=n())
import_hist <-  tx_cum_imports %>%
    ggplot(aes(count)) + geom_histogram() +
      labs(x = "Cumulative County Importations")

save_plot(filename = "figs/tx_import_hist.pdf", plot = import_hist, base_height = 4, base_aspect_ratio = 1.3)
import_hist

tx_import_map <- map_data(map = "county") %>% filter(region=="texas") %>%
  left_join(tx_cum_imports, by=c("subregion" = "county")) %>%
  ggplot(aes(x=long, y=lat, fill = count, group = subregion)) +
  geom_polygon(color = "gray", size=0.25) +
  scale_fill_continuous(na.value="white", low = "gray", high = "red")+
  theme(axis.line=element_blank(),
     axis.text.x=element_blank(),
     axis.text.y=element_blank(),
     axis.ticks=element_blank(),
     axis.title.x=element_blank(),
     axis.title.y=element_blank(),
     legend.position = c(0.15, 0.8))

save_plot(filename = "figs/tx_import_map.pdf", plot = tx_import_map, base_height = 5, base_aspect_ratio = 1)
tx_import_map

```


## Updating R0 

```{r}

dpois(x = 0, lambda = 1.5)^3

mle_ex <- data_frame(rnots = seq(0, 10, length.out = 100))

mle_ex_plot <- mle_ex %>% mutate(likelihood = map(rnots, ~intro_like_vec(rnot=., num_intros=3, distribution = "pois"))) %>%
  unnest(likelihood) %>%
  # mutate(likelihood = normalize_vector(likelihood)) %>%
  ggplot(aes(rnots, likelihood)) + geom_line()



overdisp_plot <- data_frame(rnot = seq(0.01, 1, length.out = 1000)) %>%
  mutate(overdispersion = unlist(purrr::map(rnot, ~find_overdispersion(.x)))) %>%
  ggplot(aes(rnot, overdispersion)) + geom_point(size=1) +
  geom_vline(xintercept=0.5777, lty=2)

save_plot(filename = "figs/overdisp_plot.pdf", plot = overdisp_plot, base_height = 4, base_aspect_ratio = 1.3)

```

